name: CI
 
on:
  push:
    branches: [ master ]
    paths-ignore: [ README.md ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle (skipping tests for now)
        run: ./gradlew build -x test
